name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  front-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installation de Node
        uses: actions/setup-node@v2

      - name: Installation des dépendances
        run: npm install

      - name: Analyse du code
        run: npm run analyse

      - name: Format
        run: |
          npm run format
          git diff --exit-code || (echo "Il y a des avertissements dans le format" && exit 1)

  back-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Installation des dépendances
        run: composer install

      - name: Analyse du code
        run: composer analyse

      - name: Format
        run: composer format:check

      - name: Tests Unitaires
        run: composer test:unit

  e2e-testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admincoderensemble
          POSTGRES_PASSWORD: cedb55
          POSTGRES_DB: coderensembledb

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installation de Node
        uses: actions/setup-node@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Installation des dépendances Front
        working-directory: Front
        run: npm install

      - name: Installation des dépendances Back
        working-directory: Back
        run: composer install

      - name: Migrations Doctrine
        working-directory: Back
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Ajout des fixtures
        working-directory: Back
        run: php bin/console doctrine:fixtures:load --no-interaction

      - name: Lancement des tests e2e
        working-directory: Front
        run: npm run test:e2e
